const INCREMENT_LEVEL = 'INCREMENT_LEVEL';
const INCREMENT_SCORE = 'INCREMENT_SCORE';
const DECREMENT_LIFE_TIME = 'DECREMENT_LIFE_TIME';
const SUCCESS_GET_LIST_WORDS = 'SUCCESS_GET_LIST_WORDS';
const SUCCESS_GET_LIST_HIGH_SCORE = 'SUCCESS_GET_LIST_HIGH_SCORE';
const ADD_ITEM_LIST_HIGH_SCORE = 'ADD_ITEM_LIST_HIGH_SCORE';
const CHANGE_CURRENT_WORD = 'CHANGE_CURRENT_WORD';
const SUCCESS_CHANGE_CURRENT_WORD = 'CHANGE_CURRENT_WORD';
const RESTART_GAME = 'RESTART_GAME';

export {
  INCREMENT_LEVEL,
  SUCCESS_CHANGE_CURRENT_WORD,
  DECREMENT_LIFE_TIME,
  SUCCESS_GET_LIST_HIGH_SCORE,
  CHANGE_CURRENT_WORD,
  INCREMENT_SCORE,
  ADD_ITEM_LIST_HIGH_SCORE,
  SUCCESS_GET_LIST_WORDS,
  RESTART_GAME,
};
